name: instabug_http_client
description:
  This package is an add on to instabug_flutter. It intercepts any requests performed
  with http Package and sends them to the report that will be sent to the dashboard.
version: 3.0.0-dart3
publish_to: http://nexus.axlehire.com:7777
axlehire_project_type: package
homepage: https://github.com/Instabug/Instabug-Flutter#readme

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  instabug_flutter: '>=11.0.0 <12.0.0'
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
